catalog_name: mlops_course
schema_name: merktrouw


prd:
  catalog_name: mlops_course
  schema_name: merktrouw
  pipeline_id: f43a5e1c-b6a5-422f-801c-06bd7b8de21d?o=7110057662512390
acc:
  catalog_name: mlops_course
  schema_name: merktrouw
  pipeline_id: f43a5e1c-b6a5-422f-801c-06bd7b8de21d?o=7110057662512390
dev:
  catalog_name: mlops_course
  schema_name: merktrouw
  pipeline_id: f43a5e1c-b6a5-422f-801c-06bd7b8de21d?o=7110057662512390

experiment_name_custom: /Shared/experiments/merktrouw-custom

parameters:
  learning_rate: 0.01
  n_estimators: 100
  max_depth: 6

num_features:
  - 'had_eerder_merk'
  - 'mobipas'
  - 'had_factuur_13_mnd'
  - 'had_factuur_ldg_13_mnd'
  - 'wpl_aantal_facturen_13_mnd'
  - 'wpl_aantal_facturen_ldg_13_mnd'
  - 'wpl_bedrag_13_mnd'
  - 'wpl_bedrag_ldg_13_mnd'
  - 'is_hybride'

cat_features:
  - 'geslacht'
  - 'nieuw_gebruikt_huidig'
  - 'auto_segment_huidig'

target: merktrouw
